# Common Make targets for simulating MachSuite in gem5.
#
# Requirements:
#   - ALADDIN_HOME needs to be defined as an environment variable.
#   - libgem5aladdin.a ("make lib" under $(ALADDIN_HOME)/gem5).

gem5:
	$(MAKE) CFLAGS="-static -DGEM5_HARNESS -I$(ALADDIN_HOME)" \
          LFLAGS="-L$(ALADDIN_HOME)/gem5 -lgem5aladdin" \
          CC=gcc
