ACCEL_NAME = test_command_queue
SRCS = test_command_queue.c
BMARK_SPECIFIC_CFLAGS=-DDMA_INTERFACE_V3
export WORKLOAD=store_kernel

include ../../common/Makefile.tracer
include ../../common/Makefile.gem5
