ACCEL_NAME = test_array_func_arg
SRCS = test_array_func_arg.c
BMARK_SPECIFIC_CFLAGS = -DDMA_INTERFACE_V3
export WORKLOAD=kernel

include ../../common/Makefile.tracer
include ../../common/Makefile.gem5
