ACCEL_NAME = test_host_load_store
SRCS = test_host_load_store.c
BMARK_SPECIFIC_CFLAGS=-DDMA_INTERFACE_V3
export WORKLOAD=store_kernel

include ../../common/Makefile.tracer
include ../../common/Makefile.gem5
