ACCEL_NAME = test_multiple_accelerators
SRCS = test_multiple_accelerators.c
BMARK_SPECIFIC_CFLAGS=-DDMA_INTERFACE_V3
export WORKLOAD=store_kernel

include ../../common/Makefile.tracer
include ../../common/Makefile.gem5
