import sys

Import('*')

SimObject('CacheDatapath.py')

Source('../common/BaseDatapath.cpp')
Source('../common/DDDG.cpp')
Source('../common/file_func.cpp')
Source('../common/generic_func.cpp')
Source('../common/opcode_func.cpp')

Source('aladdin_tlb.cc')
Source('CacheDatapath.cpp')

DebugFlag('CacheDatapath')
