#### NOTES ####
# Define ACCEL_NAME, TRACER_HOME, ALADDIN_HOME, WORKLOAD, SRCS before including
# this.
###############

.PHONY: trace clean run autotrace check-env

EXEC = $(ACCEL_NAME)

TRACER = $(TRACER_HOME)/full-trace/full_trace.so
LOGGER = $(TRACER_HOME)/profile-func/trace_logger.llvm
COMMON_TEMP_DIR = obj
MODE = LLVM_TRACE

LLVM_OBJS = $(patsubst %.c, $(COMMON_TEMP_DIR)/%-opt.llvm, $(SRCS))

trace: $(COMMON_TEMP_DIR)/$(EXEC)-instrumented

# To have traces generated automatically, set the environment variable
# TRACE_OUTPUT_DIR to a directory where you want the traces to eventually go,
# then build this target. The trace will get split into separate traces per
# function, and all files ending in _trace will get copied there.
autotrace: trace check-env
	$(COMMON_TEMP_DIR)/$(EXEC)-instrumented

check-env:
ifeq ($(TRACE_OUTPUT_DIR),)
	$(error TRACE_OUTPUT_DIR is not set!)
endif

#########################################################
#        INSTRUMENTATION AND TRACE FILE GENERATION      #
#########################################################

$(COMMON_TEMP_DIR)/full.llvm: $(LLVM_OBJS)
	llvm-link -o $@ $^ $(LOGGER)

$(COMMON_TEMP_DIR)/full.s: $(COMMON_TEMP_DIR)/full.llvm
	llc -O0 -disable-fp-elim -filetype=asm -o $@ $<

$(COMMON_TEMP_DIR)/$(EXEC)-instrumented: $(COMMON_TEMP_DIR)/full.s
	$(CXX) -static -O0 -fno-inline -o $@ $< -lm -lz

$(COMMON_TEMP_DIR)/%-opt.llvm: %.c
	mkdir -p $(COMMON_TEMP_DIR)
	clang -static -g -O1 -S -fno-slp-vectorize -fno-vectorize -fno-unroll-loops \
        -fno-inline -fno-builtin -emit-llvm \
        -I$(ALADDIN_HOME)/gem5 \
        -D$(MODE) \
        $(BMARK_SPECIFIC_CFLAGS) \
        -o $(COMMON_TEMP_DIR)/$*.llvm $<
	opt -S -load=$(TRACER) -fulltrace $(COMMON_TEMP_DIR)/$*.llvm -o $@

clean:
	rm -rf $(COMMON_TEMP_DIR)
	rm -f *.llvm
	rm -f *.o
	rm -f dynamic_trace.gz
	rm -f static_trace
	rm -f *-instrumented
	rm -f full.s
