# Common components to all tests.

.PHONY: test run

GEM5_DEPS = $(ALADDIN_HOME)/gem5/aladdin_sys_connection.cpp \
            $(ALADDIN_HOME)/gem5/aladdin_sys_constants.cpp

GEM5_CFLAGS = -static -march=nocona -msse -mfpmath=sse \
                   -mno-80387 -msoft-float \
                   -fno-exceptions \
                   -I$(ALADDIN_HOME)/gem5

test: $(TEST_BIN)

$(TEST_BIN): $(SRCS)
	$(CXX) $(GEM5_CFLAGS) $(SRCS) $(GEM5_DEPS) -DACCEL_SIMULATE_MODE -o $(TEST_BIN)

run: $(TEST_BIN)
	sh run.sh
