#!/usr/bin/env python
import sys
import os

kernels = {
  'aes-aes' : 'gf_alog,gf_log,gf_mulinv,rj_sbox,rj_xtime,aes_subBytes,aes_addRoundKey,aes_addRoundKey_cpy,aes_shiftRows,aes_mixColumns,aes_expandEncKey,aes256_encrypt_ecb',
  #'backprop-backprop':'sigmoid,update_layer,update,propagate_error_out,propagate_error_layer,update_weights,propagate_errors,comp_error,backprop',
  'bfs-bulk' : 'bfs',
  'bfs-queue' : 'bfs',
  'kmp-kmp' : 'CPF,kmp',
  'fft-strided' : 'fft',
  'fft-transpose':'twiddles8,loadx8,loady8,fft1D_512',
  'gemm-blocked': 'bbgemm',
  'gemm-ncubed' : 'gemm',
  'md-grid':'md',
  'md-knn':'md_kernel',
  'nw-nw' : 'needwun',
  'sort-merge' : 'merge,mergesort',
  'sort-radix' : 'local_scan,sum_scan,last_step_scan,init,hist,update,ss_sort',
  'spmv-crs' : 'spmv',
  'spmv-ellpack' : 'ellpack',
  'stencil-stencil2d' : 'stencil',
  'stencil-stencil3d' : 'stencil3d',
  'viterbi-viterbi' : 'viterbi',
}
array_names = {
 'aes-aes' : ['ctx','k','buf','rcon','sbox'],
 #'backprop-backprop' : ['weights','inputs','targets','changeMat','activations','deltas','layer_size'],
 'bfs-bulk' : ['nodes','edges','level','level_counts'],
 'bfs-queue' : ['queue','nodes','edges','level','level_counts'],
 'kmp-kmp' :['pattern','input','kmpNext'],
 'fft-strided' : ['real','img','real_twid','img_twid'],
 'fft-transpose':['reversed','DATA_x','DATA_y','data_x','data_y','smem','work_x','work_y'],
 'gemm-blocked':['m1','m2','prod'],
 'gemm-ncubed' :['m1','m2','prod'],
 'md-knn':['d_force_x','d_force_y','d_force_z','position_x','position_y','position_z','NL'],
 'md-grid' : ['n_points','d_force','position'],
 'nw-nw' : ['SEQA','SEQB','allignedA','allignedB','A','ptr'],
 'sort-merge' : ['temp','a'],
 'sort-radix' :['a','b','bucket','sum'],
 'spmv-crs' :['val','cols','rowDelimiters','vec','out'],
 'spmv-ellpack' :['nzval','cols','vec','out'],
 'stencil-stencil2d' :['orig','sol','filter'],
 'stencil-stencil3d' : ['orig','sol'],
 'viterbi-viterbi' : ['Obs','transMat','obsLik','v'],
}
array_partition_type = {
 'aes-aes' : ['cyclic','cyclic','cyclic','complete','cyclic'],
 #'backprop-backprop' : ['cyclic','cyclic','cyclic','cyclic','cyclic','cyclic','cyclic'],
 'bfs-bulk'  :['cyclic','cyclic','cyclic','cyclic'],
 'bfs-queue' :['cyclic','cyclic','cyclic','cyclic','cyclic'],
 'kmp-kmp'  :['cyclic' ,'cyclic','cyclic'],
 'fft-strided'  :['cyclic','cyclic','cyclic','cyclic'],
 'fft-transpose' :['complete','cyclic','cyclic','complete','complete','cyclic','cyclic','cyclic'],
 'gemm-blocked':['cyclic','cyclic','cyclic'],
 'gemm-ncubed' :['cyclic','cyclic','cyclic'],
 'md-knn' :['cyclic','cyclic','cyclic','cyclic','cyclic','cyclic','cyclic'],
 'md-grid' :['cyclic','cyclic','cyclic'],
 'nw-nw' :['cyclic','cyclic','cyclic','cyclic','cyclic','cyclic'],
 'sort-merge' :['cyclic','cyclic'],
 'sort-radix' :['cyclic','cyclic','cyclic','cyclic'],
 'spmv-crs' :['cyclic','cyclic','cyclic','cyclic','cyclic'],
 'spmv-ellpack' :['cyclic','cyclic','cyclic','cyclic'],
 'stencil-stencil2d' :['cyclic','cyclic','complete'],
 'stencil-stencil3d' :['cyclic','cyclic'],
 'viterbi-viterbi' :['cyclic','cyclic','cyclic','cyclic'],
}
array_size = {
 'aes-aes' : ['96','32','16','1','256'],
 #'backprop-backprop' : ['200','20','50','300','30','30','3'],
 'bfs-bulk'  :['512',  '4096', '256',  '10'],
 'bfs-queue' :['256',   '512',  '4096',  '256',  '10'],
 'kmp-kmp'  :['4'      ,'32411'   ,'4'],
 'fft-strided'  :['1024','1024','1024'    ,'1024'],
 'fft-transpose' :['8' ,'512' ,'512','8','8','576','512','512'],
 'gemm-blocked' :['4096','4096','4096'],
 'gemm-ncubed' :['4096','4096','4096'],
 'md-knn' :['256','256','256','256','256','256','4096'],
 'md-grid' :['64','1920','1920'],
 'nw-nw' :['128' ,'128' ,'256','256','16641','16641'],
 'sort-merge' :['4096','4096'],
 'sort-radix' :['2048','2048','2048'  ,'128'],
 'spmv-crs' :['1666','1666','495','494','494'],
 'spmv-ellpack' :['4940' ,'4940','494','494'],
 'stencil-stencil2d' :['8192','8192','9'],
 'stencil-stencil3d' :['16384','16384'],
 'viterbi-viterbi' :['128','4096'    ,'4096'  ,'4096']
}
#in bytes
array_wordsize = {
 'aes-aes' : ['uint8','uint8','uint8','uint8','uint8'],
 #'backprop-backprop' : ['double','double','double','double','double','double','int'],
 'bfs-bulk' : ['uint64','uint64','uint8','uint64'],
 'bfs-queue' : ['uint64','uint64','uint64','uint8','uint64'],
 'kmp-kmp' :['char','char','int'],
 'fft-strided' : ['double','double','double','double'],
 'fft-transpose':['int','double','double','double','double','double','double','double'],
 'gemm-blocked':['int','int','int'],
 'gemm-ncubed' :['int','int','int'],
 'md-knn':['double','double','double','double','double','double','double'],
 'md-grid' : ['int','double','double'],
 'nw-nw' : ['char','char','char','char','int','char'],
 'sort-merge' : ['int','int'],
 'sort-radix' :['int','int','int','int'],
 'spmv-crs' :['double','int','int','double','double'],
 'spmv-ellpack' :['double','int','double','double'],
 'stencil-stencil2d' :['int','int','int'],
 'stencil-stencil3d' : ['int','int'],
 'viterbi-viterbi' : ['int','float','float','float'],
}
loop_tripcounts = {
  'aes-aes-aes_subBytes-122' : 16,
  'aes-aes-aes_addRoundKey-130' : 16,
  'aes-aes-aes_addRoundKey_cpy-138' : 16,
  'aes-aes-aes256_encrypt_ecb-198' : 32,
  'aes-aes-aes256_encrypt_ecb-201' : 8,
  'aes-aes-aes256_encrypt_ecb-207' : 13,
  'bfs-bulk-bfs-68' : 1, #not known in design time, unroll factor 1
  'bfs-bulk-bfs-53' : 10,
  'bfs-bulk-bfs-57' : 0, #input dependent, always flatten
  'bfs-queue-bfs-63' : 1,
  'bfs-queue-bfs-70' : 0,
  'kmp-kmp-CPF-40' : 32411,
  'kmp-kmp-CPF-41' : 1,
  'kmp-kmp-kmp-60' : 32411,
  'kmp-kmp-kmp-61' : 1,
  'fft-strided-fft-8' : 10,
  'fft-strided-fft-9' : 1,
  'fft-transpose-twiddles8-55' : 8,
  'fft-transpose-fft1D_512-154' : 64,
  'fft-transpose-fft1D_512-201' : 64,
  'fft-transpose-fft1D_512-215' : 64,
  'fft-transpose-fft1D_512-231' : 64,
  'fft-transpose-fft1D_512-246' : 64,
  'fft-transpose-fft1D_512-271' : 64,
  'fft-transpose-fft1D_512-321' : 64,
  'fft-transpose-fft1D_512-336' : 64,
  'fft-transpose-fft1D_512-352' : 64,
  'fft-transpose-fft1D_512-367' : 64,
  'fft-transpose-fft1D_512-392' : 64,
  'gemm-blocked-bbgemm-43': 8,
  'gemm-blocked-bbgemm-44': 8,
  'gemm-blocked-bbgemm-45': 64,
  'gemm-blocked-bbgemm-46': 8,
  'gemm-blocked-bbgemm-50': 8,
  'gemm-ncubed-gemm-44': 64,
  'gemm-ncubed-gemm-45': 64,
  'gemm-ncubed-gemm-48': 64,
  'md-grid-md-46' : 4,
  'md-grid-md-47' : 4,
  'md-grid-md-48' : 4,
  'md-grid-md-50' : 1,
  'md-grid-md-51' : 1,
  'md-grid-md-52' : 1,
  'md-grid-md-56' : 1,
  'md-grid-md-62' : 1,
  'md-knn-md_kernel-51' : 256,
  'md-knn-md_kernel-58' : 16,
  'nw-nw-needwun-45' : 129,
  'nw-nw-needwun-49' : 129,
  'nw-nw-needwun-54' : 128,
  'nw-nw-needwun-55' : 128,
  'nw-nw-needwun-99' : 128,
  'sort-merge-merge-37' : 2048,
  'sort-merge-merge-41' : 2048,
  'sort-merge-merge-48' : 1,
  'sort-merge-mergesort-69' : 1,
  'sort-merge-mergesort-70' : 1,
  'sort-radix-local_scan-41' : 128,
  'sort-radix-local_scan-42' : 16,
  'sort-radix-sum_scan-53' : 128,
  'sort-radix-last_step_scan-62' : 128,
  'sort-radix-last_step_scan-63' : 16,
  'sort-radix-init-73' : 2048,
  'sort-radix-hist-82' : 512,
  'sort-radix-hist-83' : 4,
  'sort-radix-hist-96' : 512,
  'sort-radix-hist-97' : 4,
  'sort-radix-ss_sort-110' : 1,
  'spmv-crs-spmv-41' : 494,
  'spmv-crs-spmv-45' : 1,
  'spmv-ellpack-ellpack-41' : 494,
  'spmv-ellpack-ellpack-43' : 10,
  'stencil-stencil2d-stencil-38' : 126,
  'stencil-stencil2d-stencil-39' : 62,
  'stencil-stencil2d-stencil-40' : 3,
  'stencil-stencil2d-stencil-41' : 3,
  'stencil-stencil3d-stencil3d-42' : 30,
  'stencil-stencil3d-stencil3d-43' : 30,
  'stencil-stencil3d-stencil3d-44' : 14,
  'viterbi-viterbi-viterbi-41' : 128,
  'viterbi-viterbi-viterbi-43' : 32,
  'viterbi-viterbi-viterbi-44' : 32,
  'viterbi-viterbi-viterbi-55' : 32,
}

def sizeinbytes (type):
  if type == 'uint8' or type == 'char':
    return 1
  elif type == 'int' or type == 'float':
    return 4
  elif type == 'double' or type == 'uint64':
    return 8

