ACCEL_NAME = test_dma_store_order
SRCS = test_dma_store_order.c
BMARK_SPECIFIC_CFLAGS=-DDMA_INTERFACE_V3
export WORKLOAD=store_kernel

include ../../common/Makefile.tracer
include ../../common/Makefile.gem5
