ACCEL_NAME = test_hybrid_simd
SRCS = test_hybrid_simd.c
BMARK_SPECIFIC_CFLAGS = -DDMA_INTERFACE_V3
export WORKLOAD=store_kernel

include ../../common/Makefile.tracer
include ../../common/Makefile.gem5
