ACCEL_NAME = test_multiple_invocations
SRCS = test_multiple_invocations.c
BMARK_SPECIFIC_CFLAGS = -DDMA_INTERFACE_V3
export WORKLOAD=store_kernel

include ../../common/Makefile.tracer
include ../../common/Makefile.gem5
